### ISSUE TITLE
Mautic 5.1.0 - Mailjet API seems not to be supported? (only SMTP)

### ISSUE THREAD

**Issue by dsp76** [Leuchtfeuer/mautic-MailjetAdapter-bundle#5]
API seems not to be supported? Can't save the protocol.

<img width="248" alt="image" src="https://github.com/user-attachments/assets/e6825510-f4cf-4e45-86f4-5f8aa1183528">

**Comment by MadlenF** [comment]
Close the issue as the test was conducted with an outdated version.
